// Generated by gencpp from file planner/ControlSequence.msg
// DO NOT EDIT!


#ifndef PLANNER_MESSAGE_CONTROLSEQUENCE_H
#define PLANNER_MESSAGE_CONTROLSEQUENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <planner/Control.h>

namespace planner
{
template <class ContainerAllocator>
struct ControlSequence_
{
  typedef ControlSequence_<ContainerAllocator> Type;

  ControlSequence_()
    : controls()  {
    }
  ControlSequence_(const ContainerAllocator& _alloc)
    : controls(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::planner::Control_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::planner::Control_<ContainerAllocator> >::other >  _controls_type;
  _controls_type controls;





  typedef boost::shared_ptr< ::planner::ControlSequence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planner::ControlSequence_<ContainerAllocator> const> ConstPtr;

}; // struct ControlSequence_

typedef ::planner::ControlSequence_<std::allocator<void> > ControlSequence;

typedef boost::shared_ptr< ::planner::ControlSequence > ControlSequencePtr;
typedef boost::shared_ptr< ::planner::ControlSequence const> ControlSequenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planner::ControlSequence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planner::ControlSequence_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planner

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'planner': ['/home/csc/CS4278-5478-Assignment3/src/planner/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planner::ControlSequence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planner::ControlSequence_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ControlSequence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planner::ControlSequence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ControlSequence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planner::ControlSequence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planner::ControlSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b73a45fc9f216f397bef7a4afdff8b2";
  }

  static const char* value(const ::planner::ControlSequence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b73a45fc9f216f3ULL;
  static const uint64_t static_value2 = 0x97bef7a4afdff8b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::planner::ControlSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planner/ControlSequence";
  }

  static const char* value(const ::planner::ControlSequence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planner::ControlSequence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Control[] controls\n\
================================================================================\n\
MSG: planner/Control\n\
float64 v\n\
float64 w\n\
";
  }

  static const char* value(const ::planner::ControlSequence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planner::ControlSequence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controls);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlSequence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planner::ControlSequence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planner::ControlSequence_<ContainerAllocator>& v)
  {
    s << indent << "controls[]" << std::endl;
    for (size_t i = 0; i < v.controls.size(); ++i)
    {
      s << indent << "  controls[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::planner::Control_<ContainerAllocator> >::stream(s, indent + "    ", v.controls[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNER_MESSAGE_CONTROLSEQUENCE_H
